less:
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shopArticle/partials/articleBulkOrderPrices.less
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shopArticle/partials/articleStockMessage.less
