less:
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shippingAndPayment/paypalPostOrderPayPalLink.less
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shippingAndPayment/selectPayment.less
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shippingAndPayment/selectShippingGroup.less
