less:
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shopCategory/shopCategorySubcategoryteaserList.less
   - /bundles/chameleonsystemchameleonshoptheme/snippets/pkgShop/shopCategory/shopCategoryDescription.less
